server:
  port: 8088

spring:
  application:
    name: service-provider
  kafka:
    bootstrap-servers: 47.106.176.177:9092
    consumer:
      group-id: defaultGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topic: mine.kafka

eureka:
#  更改Eureka更新频率将打破服务器的自我保护功能，生产环境下不建议自定义这些配置。
#  instance:
##    续约更新时间间隔(默认30秒)
#    lease-renewal-interval-in-seconds: 30
##    续约到期时间(默认90秒)
#    lease-expiration-duration-in-seconds: 90
  client:
#    开启健康检查
    healthcheck:
      enabled: true
    service-url:
#      设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/