server:
  port: 8087

spring:
  application:
    name: service-consumer-ribbon
  kafka:
    bootstrap-servers: 47.106.176.177:9092
    consumer:
      group-id: digital-cockpit-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topic: mine.kafka

eureka:
#  更改Eureka更新频率将打破服务器的自我保护功能，生产环境下不建议自定义这些配置。
  instance:
    prefer-ip-address: true
#    续约更新时间间隔(默认30秒)
#    lease-renewal-interval-in-seconds: 30
#    续约到期时间(默认90秒)
#    lease-expiration-duration-in-seconds: 90
  client:
#    开启健康检查
    healthcheck:
      enabled: true
    service-url:
#      设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

#开启熔断,用Finchley版本的话可能无法识别，会无法开启
feign:
  hystrix:
    enabled: true
