server:
  port: 8086

spring:
  application:
    name: service-gateway
  cloud:
#    springCloud的网关配置，配置方法详见：
#    https://cloud.spring.io/spring-cloud-static/spring-cloud-gateway/2.1.0.M3/single/spring-cloud-gateway.html
    gateway:
#      default-filters里面可以定义一些共同的filter，对所有路由都起作用
#      default-filters:
      discovery:
        locator:
#          是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。
#          默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
#          路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: false
#      具体的路由信息，是一个数组,每个路由基本包含id、uri、predicates和filters等
      routes:
#      ------------------------------------------------------------------
#        这个路由的唯一id，不定义的话为一个uuid
      - id: 163
#        http请求为lb(load balancing负载均衡)://前缀 + 服务id；ws请求为lb:ws://前缀 + 服务id；表示将请求负载到哪一个服务上
        uri: http://www.163.com/
#        这个路由的请求匹配规则，只有符合这个规则的请求才会走这个路由。为一个数组，每个规则为并且的关系
        predicates:
        - Path=/163/**
#        请求转发前的filter，为一个数组。
#        filters:
#        - StripPrefix=1
#      ------------------------------------------------------------------
      - id: baidu
        uri: http://www.baidu.com/
        predicates:
        - Path=/baidu/**
#      ------------------------------------------------------------------
      - id: taobao
        uri: http://www.taobao.com/
        predicates:
        - Path=/taobao/**
#      ------------------------------------------------------------------
      - id: hello
        uri: http://localhost:8087/hello/feign
        predicates:
        - Path=/hello/**
#      ------------------------------------------------------------------

eureka:
#  更改Eureka更新频率将打破服务器的自我保护功能，生产环境下不建议自定义这些配置。
  instance:
    prefer-ip-address: true
#    续约更新时间间隔(默认30秒)
#    lease-renewal-interval-in-seconds: 30
#    续约到期时间(默认90秒)
#    lease-expiration-duration-in-seconds: 90
  client:
#    开启健康检查
    healthcheck:
      enabled: true
    service-url:
#      设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
