server:
  port: 8763

spring:
  application:
    name: eureka-server-peer3

eureka:
  instance:
    hostname: peer3
#  server:
##    开启自我保护，让Eureka集群更加的健壮、稳定。
#    enable-self-preservation: false
##    清理间隔(单位毫秒，默认是60*1000)
#    eviction-interval-timer-in-ms: 10000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/